import Script from 'next/script'

import 'bootstrap/dist/css/bootstrap.css';

export const metadata = {
  title: "star",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link href="/css/liderCustom.css" rel="stylesheet" type="text/css"/>
      </head>
      <body>
        {children}
                   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script> 
<script src="/js/custom.js"></script>
      </body>
    </html>
  );
}
